### ISSUE TITLE
Flagged messages doesn't appear in "Flagged messages"

### ISSUE THREAD

**Issue by matthesatox** [open-xchange/ox-coi#571] opened 2020-05-19 09:12 UTC
**Describe the bug**
Flagged messages doesn't appear in "Flagged messages"

**To Reproduce**
Occurrence: [always / 5 out of 10 times / rarely]
1. Go to Chat
2. Long tab on an unflagged message
3. Select "Flag/Unflag"
4. Go to profile
5. Open "Flagged messages"

**Expected behavior**
Previous flagged messages should appear in "Flagged messages"

**Screenshots**

**App information (please complete the following information):**
 - App version: 0.700.1 (517)
 - Plugin version:
 - Delta Chat Core version:
 - Flutter version:

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max, iPhone SE
 - OS: iOS 13.5 final, iOS 13.4.1 final

**Additional context**

[Internal Bug Tracker](https://jira.open-xchange.com/browse/OT-???).

**Comment by Boehrsi** [comment] 2020-05-20 11:17
Duplicate of #568.

**Closed by Boehrsi** 2020-05-20 11:17 UTC
Labels: bug
