### ISSUE TITLE
3 Dots behind every message sendet from OX-Coi to Delta Chat

### ISSUE THREAD

**Issue by webratte** [open-xchange/ox-coi#221] opened 2019-10-23 05:14 UTC
**Describe the bug**
If I send a message from the OX-Coi Android App to the Delta Chat Android- and Desktop Client I have behind every message 3 Dots [...]

See also the attached screenshots

**To Reproduce**
Occurrence: always
1. Send a message via OX-Coi Android App and receive this message via Delta Chat client
2. See what I described

**App information (please complete the following information):**
 - App version: OX-Coi V. beta-2 (2002) Delta Chat V.0.510.1 
 - Delta Chat Core version: I don't know
 - Flutter version: I dont know

**Smartphone (please complete the following information):**
 - Device: Huawei nova
 - OS: Android 7.0

**Additional context**
I have no idea is this a OX issue or a Delta Chat issue.

But I'm sure the OX team and the Delta Chat team have to work together and have to keep there clients 100% compatible.
Only if the good boys work together there is a chance against the big players.

I think with Chat over E-mail there is a realistic chance to replace WhatsApp with E-mail ;-)

I also opened a issue for Delta Chat:
https://github.com/deltachat/deltachat-android/issues/1082

![ox-coi](https://user-images.githubusercontent.com/6864851/67359802-9a8d5880-f564-11e9-8067-d7da3c875a6b.png)
![Deltachat](https://user-images.githubusercontent.com/6864851/67359803-9a8d5880-f564-11e9-9f7b-b5a3d89a389c.png)

**Comment by webratte** [comment] 2019-10-23 20:03
After hours of playing around and reinstalling OX-Coi it seems to work again.

So I will close this issue.
I will test more things. If I will find other things, I will reopen it.

**Comment by webratte** [comment] 2019-10-23 21:08
It seems this happens, if I switch off encryption and only with my GMX Account not with Mailbox.org

**Comment by webratte** [comment] 2019-10-24 05:17
Here are the concerned messages.

One is the sent message from the deltachat folder in the GMX account.
And the other is the received message from the deltachat folder in the mailbox.org account.

[messagesGMXtoMAILBOX_ORG.zip](https://github.com/deltachat/deltachat-android/files/3765821/messagesGMXtoMAILBOX_ORG.zip)

**Comment by Boehrsi** [comment] 2019-10-25 11:11
Thanks for reporting that issues and providing all those details. We will have a look what exactly the problem is

**Comment by webratte** [comment] 2019-10-25 17:43
Please take also also a look to the linked issue for Delta Chat.

So I have not all info to duplicate ;-)

**Comment by Hocuri** [comment] 2020-05-01 18:06
This is an issue with DC-Core and GMX.

**Comment by Boehrsi** [comment] 2020-05-05 06:23
Thanks for the additional information, I will double check the general functionality (sending / receiving messages without appended three dots) on one of our testing backends, which normally works fine to ensure no general issue exists.

**Comment by Boehrsi** [comment] 2020-05-11 15:28
Fixed with the latest app + DCC update. Will be integrated in the next release. 
The fix is about the general problem, potential provider specific issues will be opened (if they exist) separately. Closing this issue for now.

**Closed by Boehrsi** 2020-05-11 15:28 UTC
Labels: bug, needs verification, requested / user report
