### ISSUE TITLE
Searching for a manual added user in contacts leads to strange UI behaviour

### ISSUE THREAD

**Issue by matthesatox** [open-xchange/ox-coi#464] opened 2020-03-23 08:58 UTC
**Describe the bug**
Searching for a manual added user in contacts leads to strange UI behaviour. The newly added user is once in the contact list (Screenshot 1). If I search for the user, the user is shown multiple times in the search result set (Screenshot 2). After closing the search, the results are still visible in UI (Screenshot 3) Only switching to one of the other "tabs" like "Chats" or "Profile" and going back to "Contacts" refresh's the UI for contacts.

**To Reproduce**
Occurrence: always
1. Go to 'Contacts'
2. Click on Icon for adding a new user
3. Seit name and email for new user
4. Save the changes
5. Search for the newly added user

**Expected behavior**
The newly added user should only be shown once in the result. After closing the search, the UI should refresh automatically and show the normal view of contact.

**Screenshots**
![Screenshot_3](https://user-images.githubusercontent.com/62440505/77299116-4beb1280-6cec-11ea-968e-5bffad7cf9f4.jpeg)
![Screenshot_2](https://user-images.githubusercontent.com/62440505/77299126-4f7e9980-6cec-11ea-8675-c7bb10e3c1cc.jpeg)
![Screenshot_1](https://user-images.githubusercontent.com/62440505/77299131-50173000-6cec-11ea-9c39-9e8aa5d402e9.jpeg)

**App information (please complete the following information):**
 - App version: 0.600.0 (513)
 - Plugin version:
 - Delta Chat Core version:
 - Flutter version:

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: iOS 13.4 final

**Additional context**

**Comment by phranck** [comment] 2020-03-23 10:26
@matthesatox Unfortunately, I'm not able to reproduce this behavior. Neither in iOS Simulator nor on my iPhone 11. Maybe @CihanOezkan can reproduce it?

**Comment by CihanOezkan** [comment] 2020-03-23 14:41
@matthesatox Unfortunately, I'm also not able to reproduce it.

**Comment by phranck** [comment] 2020-03-25 07:59
Okay, now I can confirm. This also happens to me.

**Comment by Boehrsi** [comment] 2020-04-28 06:18
Fixed in the latest release: https://github.com/open-xchange/ox-coi/releases/tag/0.600.3.

**Closed by Boehrsi** 2020-04-28 06:18 UTC
Labels: bug, qa-testing
