### ISSUE TITLE
Startup Crash on Android 10

### ISSUE THREAD

**Issue by schirinowski** [open-xchange/ox-coi#396] opened 2020-01-30 06:38 UTC
**Describe the bug**
The Android app crashes on each startup on my Samsung S10e with Android 10. No screen is rendered. Sent a feedback report using the Android feedback functionality with the subject of this bug as comment.

**To Reproduce**
Occurrence: always
1. Tap the OX COI icon to start the app. 

**Expected behavior**
OX COI opens. 

**Screenshots**

**App information (please complete the following information):**
 - App version: 0.450.0 (latest from Google Play Store, can't say more as app doesn't show up
 - Plugin version: n/a
 - Delta Chat Core version: n/a
 - Flutter version: n/a

**Smartphone (please complete the following information):**
 - Device: Samsung S10e
 - OS: Android 10

**Additional context**
n/a

**Comment by Boehrsi** [comment] 2020-01-30 07:59
Thanks for filing this issue. We will try to reproduce + fix this crash as fast as possible. Thanks for providing additional debug information via the Google Play debugging system. Hopefully the next release will fix this problem.

**Comment by Boehrsi** [comment] 2020-01-31 14:02
We will release a new version starting next week and this version worked well with Android 10 (at least during our tests). So I hope  this will also fix your problem.

**Comment by schirinowski** [comment] 2020-01-31 16:41
Sounds great, means you found something. 👍

**Comment by Boehrsi** [comment] 2020-02-03 07:56
Hopefully yes, as we stabilized and updated multiple components. The new version  is already available via https://play.google.com/store/apps/details?id=com.openxchange.oxcoi

**Comment by schirinowski** [comment] 2020-02-03 11:35
Updates to 0.500.1, but problems persist. The app keeps crashing during start-up. Two improvements, though: I can see the COI logo splash screen and sometimes also a list of conversations before the app force closes.

**Comment by Boehrsi** [comment] 2020-02-03 14:02
Thanks and thanks for the fast feedback, sounds like a specific problem with this specific installation, not a general Android 10 problem. Were you ever be able to start and use the app or was it broken since the very beginning.

**Comment by schirinowski** [comment] 2020-02-03 17:46
Worked like a charm from the very beginning.

**Comment by schirinowski** [comment] 2020-02-11 09:16
Had some time to test. Force stopping and starting the app again led to crashes. Deleting cache data for the app did not help either. Then I removed all data from the app, so resetting it as if it was installed fresh, makes the app not crash anymore. Setting up my account worked flawlessly.
Were there any changes before 0.450.0 in the data structure that caused the crashes?

**Comment by Boehrsi** [comment] 2020-02-11 10:30
Thanks for the efforts and the additional information, we appreciate this a lot!
In regards to breaking changes, I don't think there were any, but I will have another look, if e.g. something in combination of Android 10 + upgrade from 0.450.0 to 0.500.0 could cause the mentioned problems.
For now I'm happy the app in general is working again for you 👍

**Comment by Boehrsi** [comment] 2020-03-04 12:57
I'm closing this issue for now, as the problem is gone. In general we are currently trying to improve the stability and fix possible reasons for deadlocks and bricked apps, so hopefully we can minimize those situations in the future. Thanks again for filing this bug.

**Closed by Boehrsi** 2020-03-04 12:57 UTC
Labels: Severe, android, bug
