### ISSUE TITLE
Own messages show twice in chat

### ISSUE THREAD

**Issue by mentosmenno2** [open-xchange/ox-coi#399] opened 2020-02-02 18:22 UTC
**Describe the bug**
My own messages are shown twice in my chat. Restarting the app doesn't make the duplicates dissappear. The receiving party only received the message once (like it should)

**To Reproduce**
Occurrence: [**always** / 5 out of 10 times / rarely]
1. Go to 'a chat'
2. Send a text message

**Expected behavior**
My message is only displayed once

**Screenshots**
![Screenshot_20200202-191614_OX COI Messenger~2](https://user-images.githubusercontent.com/12169252/73617799-acca6880-4622-11ea-8b5b-0841bdb6ab04.jpg)

**App information (please complete the following information):**
 - App version: 0.500.1
 - Plugin version: [e.g. 0.4.0]
 - Delta Chat Core version: [e.g. 0.40.0]
 - Flutter version: [e.g. 1.0]

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy a50
 - OS: Android 9

**Additional context**

**Comment by Boehrsi** [comment] 2020-02-03 07:53
Thanks for the report, we will try to reproduce the problem.

**Comment by Boehrsi** [comment] 2020-02-10 07:44
Until now we weren't able to reproduce the problem with any of our devices + backends, but we continue investigating possible reasons for the problem.

**Comment by gichtl** [comment] 2020-02-22 23:41
Same problem here. It seems to be related to hotmail.com / outlook.com email address, since other providers worke fine.

**Comment by webratte** [comment] 2020-02-23 06:14
I also experienced this. But not the sent messages. I got sometimes received messages two times.
And I use a GMX Account. So it seems not related to the provider.

But could not reproduce this problem. It happens by chance.

**Comment by Boehrsi** [comment] 2020-03-09 12:37
I also encountered this once (as receiver). We will integrate an updated DCC version in one of the next releases and hopefully this helps, as the general problem seems to be pretty deep somewhere in the logic.

**Comment by Boehrsi** [comment] 2020-04-16 12:11
Will be fixed in the upcoming release.

**Closed by Boehrsi** 2020-04-16 12:11 UTC
Labels: bug, needs verification, requested / user report
